services:
  jetson:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PLATFORM: jetson
      ROS_DOMAIN_ID: "0"
    user: root
    privileged: true
    image: barracuda-onboard-jetson
    container_name: barracuda-onboard-jetson
    tty: true
    network_mode: host
    # ipc: host
    volumes:
      - ${PWD}/src:/root/ros2_ws/src

  pi:
    build:
      context: .
      dockerfile: Dockerfile
      # pi platform arg needed at build time so we can build a smaller image for it (only dependencies needed for barracuda-thrusters)
      args:
        PLATFORM: pi
    environment:
      PLATFORM: pi
      ROS_DOMAIN_ID: "0"
    user: root
    privileged: true
    image: barracuda-onboard-pi
    container_name: barracuda-onboard-pi
    tty: true
    network_mode: host
    # ipc: host
    volumes:
      - ${PWD}/src:/root/ros2_ws/src
    profiles: ["pi"]

  laptop:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PLATFORM: laptop
      ROS_DOMAIN_ID: "0"
    user: root
    privileged: true
    image: barracuda-onboard-laptop
    container_name: barracuda-onboard-laptop
    tty: true
    # network_mode: host
    # ipc: host
    ports:
      - 8765:8765
    volumes:
      - ${PWD}/src:/root/ros2_ws/src
    profiles: ["laptop"]
